test: test-stg

# Datasource
spring:
  datasource:
    url: jdbc:mysql://34.77.234.32:3306/TryOTODyn
    username: ismail
    password: OTO2023ismail+
    jpa:
      hibernate:
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  main:
     allow-bean-definition-overriding: true

  # Redis
  data:
    redis:
      host: localhost
      port: 7777

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG