# Datasource
spring:
  datasource:
    url: jdbc:mysql://10.56.112.3:3306/TryOTODyn
    username: service_write
    password: Pl.2020write
  main:
     allow-bean-definition-overriding: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

# Redis
  data:
    redis:
      host: 10.145.167.227
      port: 6379

#logging
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

