# Datasource
spring:
  datasource:
    url: jdbc:mysql://34.77.234.32:3306/TryOTODyn
    username: ismail
    password: OTO2023ismail+
  main:
     allow-bean-definition-overriding: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

# Redis
  data:
    redis:
      host: localhost
      port: 7777

#logging
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

api:
  test: 123

