test: test-stg

# Datasource
spring:
  datasource:
    url: jdbc:mysql://34.77.234.32:3306/TryOTODyn
    username: ismail
    password: OTO2023ismail+
    jpa:
      hibernate:
        naming:
          physicalstrategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Redis
  data:
    redis:
      host: localhost
      port: 7777